Swaroop Naik

23102A0001

R_Assignment_09

In [93]:
cat("The zero occurs at", 2*pi, "radians.\n")

The zero occurs at 6.283185 radians.

In [94]:
print("The zero occurs at"); print(2*pi); print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

In [95]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

In [96]:
d = date()

In [97]:
cat("Today's date is:", d, "\n" )

Today's date is: Sat Oct 24 12:38:08 2026

In [98]:
x = 1:10

In [99]:
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [100]:
cat(x, sep =" ++ ")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10

In [101]:
cat("\n")

In [102]:
cat(x, sep =" / ")

1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [103]:
x = 7

In [104]:
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [105]:
cat("The square root of",x,"is approximately", format(sqrt(x),digits=3),"\n")

The square root of 7 is approximately 2.65

In [106]:
evenno = c(2,4,6,8,10)

In [107]:
evenno

[1]  2  4  6  8 10

In [108]:
cat("The first few even numbers are:", evenno, "...\n")

The first few even numbers are: 2 4 6 8 10 ...

In [109]:
x = 1:10

In [110]:
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [111]:
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

In [112]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [113]:
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [114]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

In [115]:
paste("Everybody", "loves", "R Programming.", sep="*")

[1] "Everybody*loves*R Programming."

In [116]:
paste("Everybody", "loves", "R Programming.", sep="===")

[1] "Everybody===loves===R Programming."

In [117]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")

In [118]:
names

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

In [119]:
paste(names, "is", "a good", "person.")

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

In [120]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")

In [121]:
paste(names, "is", "a good", "person.", collapse=", and ")

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

In [122]:
paste(1, " is first", 2, " is second", 3, " is third", sep = "#")

[1] "1# is first#2# is second#3# is third"

In [123]:
paste(1, " is first ", 2, " is second ", 3, " is third ", sep = "#")

[1] "1# is first #2# is second #3# is third "

In [124]:
x = paste("Ex", 1:5, sep="_")

In [125]:
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [126]:
x[1]

[1] "Ex_1"

In [127]:
x[2]

[1] "Ex_2"

In [128]:
x[3]

[1] "Ex_3"

In [129]:
x[5]

[1] "Ex_5"

In [130]:
x = paste("Ex", 1:5, sep="_", collapse="")

In [131]:
x[1]

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [132]:
x = paste("Ex", 1:5, sep="_")

In [133]:
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [134]:
x = paste("Ex", 1:5, sep="_", collapse="")

In [135]:
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [136]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [137]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [138]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [139]:
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

In [140]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

In [141]:
x

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

In [142]:
strsplit(x, split="!")

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

In [143]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

In [144]:
x

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

In [145]:
y = strsplit(x, split = "&!")

In [146]:
y

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

In [147]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

In [148]:
x

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

In [149]:
y = strsplit(x, split = "!&")

In [150]:
y

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

In [151]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [152]:
y[[1]][2]

[1] "available! &inthe online-help"

In [153]:
y[[1]][3]

[1] NA

In [154]:
dates = c("2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27")

In [155]:
datesplt = strsplit(dates, "-")

In [156]:
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

In [157]:
datemat = matrix(unlist(datesplt), nrow = 4, ncol=3, byrow=TRUE)

In [158]:
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

In [159]:
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol=3, byrow=TRUE)

In [160]:
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [161]:
strsplit("Shalabh",split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

In [162]:
x = "R course 24.07.2022"

In [163]:
y = "Number of participants: 25"

In [164]:
nchar(x)

[1] 19

In [165]:
nchar(y)

[1] 26

In [166]:
x = "R course 24.07.2022"

In [167]:
y = "Number of participants: 25"

In [168]:
nzchar(x)

[1] TRUE

In [169]:
nzchar(y)

[1] TRUE

In [170]:
x = c("Apple", "Banana", "Cake")

In [171]:
x

[1] "Apple"  "Banana" "Cake"

In [172]:
nzchar(x)

[1] TRUE TRUE TRUE

In [173]:
y = c("Apple", "", "Cake")

In [174]:
y

[1] "Apple" ""      "Cake"

In [175]:
nzchar(y)

[1]  TRUE FALSE  TRUE

In [176]:
x = c("Apple", "Banana", "Cake")

In [177]:
nchar(x)

[1] 5 6 4

In [178]:
y = c(2, 4, 6)

In [179]:
nchar(y)

[1] 1 1 1

In [180]:
z = c(11, 222, 3333)

In [181]:
nchar(z)

[1] 2 3 4

In [182]:
z1 = c(1.1, 2.22, 3.333)

In [183]:
nchar(z1)

[1] 3 4 5

In [184]:
x = "R course will start from 24.07.2022"

In [185]:
toupper(x)

[1] "R COURSE WILL START FROM 24.07.2022"

In [186]:
z = "INDIAN INSTITUTE OF TECHNOLOGY"

In [187]:
tolower(z)

[1] "indian institute of technology"