R Programming NPTEL Week 09


---


*   Name: Swaroop Naik
*   Roll no: 23102A0001

###Strings - Display and Formatting

Print and Format with Concatenate

In [ ]:
print("The zero occurs at"); print(2*pi); print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

In [ ]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

Formatting and Display of Strings

In [ ]:
d = date

In [ ]:
cat("Today's date is:", d(), "\n")

Today's date is: Tue Sep 22 08:51:27 2026

In [ ]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
cat(x, sep = " ++ ")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10

In [ ]:
cat("\n")

In [ ]:
cat(x, sep = " / ")

1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [ ]:
x = 7

In [ ]:
cat("The sqaure of", x, "is", x^2, "!\n")

The sqaure of 7 is 49 !

In [ ]:
cat("The square root of",x,"is approximately", format(sqrt(x),digits=3),"\n")

The square root of 7 is approximately 2.65

In [ ]:
evenno = c(2,4,6,8,10)
evenno

[1]  2  4  6  8 10

In [ ]:
cat("The first few even numbers are:", evenno, "...\n")

The first few even numbers are: 2 4 6 8 10 ...

In [ ]:
x = 1:10
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

Paste Function

In [ ]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [ ]:
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [ ]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

In [ ]:
paste("Everybody", "loves", "R Programming.",
sep="*")

[1] "Everybody*loves*R Programming."

In [ ]:
 paste("Everybody", "loves", "R Programming.",
sep="===")

[1] "Everybody===loves===R Programming."

In [ ]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

In [ ]:
paste(names, "is", "a good", "person.")

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

In [ ]:
paste(names, "is", "a good", "person",
collapse=", and ")

[1] "Prof. Singh is a good person, and Mr. Venkat is a good person, and Dr. Jha is a good person"

Operations with Strings

In [ ]:
paste(1, " is first", 2, " is second", 3, " is third",
sep = "#")

[1] "1# is first#2# is second#3# is third"

In [ ]:
paste(1, " is first   ", 2, " is second   ", 3, " is third   ",
sep = "#")

[1] "1# is first   #2# is second   #3# is third   "

In [ ]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [ ]:
x[1]

[1] "Ex_1"

In [ ]:
x[2]

[1] "Ex_2"

In [ ]:
x[3]

[1] "Ex_3"

In [ ]:
x[5]

[1] "Ex_5"

In [ ]:
x = paste("Ex", 1:5, sep="_", collapse="")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [ ]:
x[1]

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [ ]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [ ]:
paste0(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [ ]:
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [ ]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [ ]:
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

String Splitting

In [ ]:
x = "The&!syntax&!of&!paste&!is!&available!
&inthe online-help"
x

[1] "The&!syntax&!of&!paste&!is!&available! \n&inthe online-help"

In [ ]:
strsplit(x, split="!")

[[1]]
[1] "The&"                  "syntax&"               "of&"
[4] "paste&"                "is"                    "&available"
[7] " \n&inthe online-help"

In [ ]:
strsplit(x, split = "&!")

[[1]]
[1] "The"                                 "syntax"
[3] "of"                                  "paste"
[5] "is!&available! \n&inthe online-help"

In [ ]:
 x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x

[1] "The&!syntax&!of&!paste&!is!&available! \n&inthe online-help"

In [ ]:
 y = strsplit(x, split = "!&")
 y

[[1]]
[1] "The&!syntax&!of&!paste&!is"      "available! \n&inthe online-help"

In [ ]:
y[[1]][1]

[1] "The&!syntax&!of&!paste&!is"

In [ ]:
y[[1]][2]

[1] "available! \n&inthe online-help"

In [ ]:
y[[1]][3]

[1] NA

In [ ]:
dates = c("2020-07-24", "2021-08-25", "2022-
09-26", "2023-10-27")

In [ ]:
datesplt = strsplit(dates, "-")
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "\n09" "26"

[[4]]
[1] "2023" "10"   "27"

In [ ]:
datemat = matrix(unlist(datesplt), nrow = 4,
ncol=3, byrow=TRUE)
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 \n09 26
[4,] 2023 10   27

In [ ]:
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4,
ncol=3, byrow=TRUE)

In [ ]:
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [ ]:
strsplit("Shalabh", split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

Manipulations with Strings and Alphabets

In [ ]:
nchar(x, type = "chars", allowNA = FALSE, keepNA = NA)

[1] 58

In [ ]:
nzchar(x, keepNA = FALSE)

[1] TRUE

In [ ]:
x = "R course 24.07.2022"

In [ ]:
y = "Number of participants: 25"

In [ ]:
nchar(x)

[1] 19

In [ ]:
nchar(y)

[1] 26

In [ ]:
nzchar(x)

[1] TRUE

In [ ]:
nzchar(y)

[1] TRUE

In [ ]:
x = c("Apple", "Banana", "Cake")
x

[1] "Apple"  "Banana" "Cake"

In [ ]:
nchar(x)

[1] 5 6 4

In [ ]:
nzchar(x)

[1] TRUE TRUE TRUE

In [ ]:
y = c("Apple", "", "Cake")
y

[1] "Apple" ""      "Cake"

In [ ]:
nzchar(y)

[1]  TRUE FALSE  TRUE

In [ ]:
y = c(2,4,6)
nchar(y)

[1] 1 1 1

In [ ]:
z = c(11, 222, 3333)

In [ ]:
nchar(z)

[1] 2 3 4

In [ ]:
z1 = c(1.1, 2.22, 3.333)

In [ ]:
nchar(z1)

[1] 3 4 5

In [ ]:
x = "R course will start from 24.07.2026"

In [ ]:
toupper(x)

[1] "R COURSE WILL START FROM 24.07.2026"

In [ ]:
z = "INDIAN INSTITUTE OF TECHNOLOGY"

In [ ]:
tolower(z)

[1] "indian institute of technology"