Name:Swaroop Naik Roll:23102A0001

This cell initializes a variable `x` with `NA` (Not Available) to demonstrate how to check for missing values in R using `is.na()`.

In [1]:
# Missing data in R

x <- NA

# Check whether x is missing
is.na(x)

[1] TRUE

This cell creates a vector `x` containing numeric values and `NA`s, then uses `is.na()` to identify the positions of missing values.

In [2]:
x <- c(11, NA, 13, NA)

x

# Check which values are NA
is.na(x)

[1] 11 NA 13 NA

[1] FALSE  TRUE FALSE  TRUE

This cell calculates the mean of a vector `x` with missing values, showing the default behavior (returning `NA`) and how to calculate the mean after removing `NA`s using `na.rm = TRUE`.

In [3]:
x <- c(11, NA, 13, NA)

# Mean including NA
mean(x)

# Mean after removing NA
mean(x, na.rm = TRUE)

[1] NA

[1] 12

This cell differentiates between `NA` and `NULL` in R. `NA` represents a missing value, while `NULL` represents an empty object. It demonstrates checking for each using `is.na()` and `is.null()` respectively.

In [4]:
x <- NA
y <- NULL

print(x)
print(y)

# Check whether they are NA
is.na(x)
is.null(y)

[1] NA
NULL

[1] TRUE

[1] TRUE

This cell shows how to find the indices (positions) of `NA` values within a vector `x` using `which(is.na(x))`.

In [5]:
x <- c(11, NA, 13, NA)

# Find positions containing NA
which(is.na(x))

[1] 2 4

This cell counts the total number of `NA` values in a vector `x` by summing the logical results of `is.na(x)` (where `TRUE` is 1 and `FALSE` is 0).

In [6]:
x <- c(11, NA, 13, NA)

sum(is.na(x))

[1] 2

This cell uses `complete.cases()` to return a logical vector indicating which elements of `x` are *not* missing (i.e., complete).

In [7]:
x <- c(11, NA, 13, NA)

complete.cases(x)

[1]  TRUE FALSE  TRUE FALSE

This cell demonstrates `na.omit()`, which returns a new vector `y` with all `NA` values removed from the original vector `x`.

In [8]:
x <- c(11, NA, 13, NA)

y <- na.omit(x)

y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

This cell compares the mean of a vector `x` with `NA`s to the mean of a new vector `y` created by removing `NA`s using `na.omit()`.

In [9]:
x <- c(11, NA, 13, NA)

y <- na.omit(x)

mean(x)
mean(y)

[1] NA

[1] 12

This cell demonstrates a simple `if` statement in R. If `x` is greater than 4, it performs a calculation, otherwise, it does nothing.

In [10]:
x <- 5

if (x > 4) {
  x * 3
}

[1] 15

This cell shows an `if` statement where the condition `x > 4` is false, so the code block inside the `if` statement is not executed, and no value is returned or printed.

In [11]:
x <- 3

if (x > 4) {
  x * 3
}

This cell demonstrates an `if` statement that prints a message if the condition `x > 3` is true.

In [12]:
x <- 6

if (x > 3) {
  print("The value is more than 3")
}

[1] "The value is more than 3"

This cell illustrates an `if-else` statement. If `x` equals 3, it subtracts 1 from `x`; otherwise, it multiplies `x` by 2.

In [13]:
x <- 5

if (x == 3) {
  x <- x - 1
} else {
  x <- 2 * x
}

x

[1] 10

This cell demonstrates a basic `if-else` statement, printing different messages based on whether `x` is greater than 3.

In [14]:
x <- 6

if (x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is more than 3"

This cell shows an `if-else` statement where the `else` block is executed because the condition `x > 3` is false.

In [15]:
x <- 2

if (x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is less than 3"

This cell demonstrates an `if-else if-else` structure. It checks multiple conditions sequentially and executes the corresponding code block.

In [16]:
x <- 5

if (x == 3) {
  x <- x - 1
} else if (x < 3) {
  x <- x + 5
} else {
  x <- 2 * x
}

x

[1] 10

This cell is another example of `if-else if-else`, where the `else if` condition (`x < 3`) is met, and `x` is updated accordingly.

In [17]:
x <- 2

if (x == 3) {
  x <- x - 1
} else if (x < 3) {
  x <- x + 5
} else {
  x <- 2 * x
}

x

[1] 7

This cell demonstrates an `if-else if-else` structure where the first `if` condition (`x == 3`) is met, and `x` is updated.

In [18]:
x <- 3

if (x == 3) {
  x <- x - 1
} else if (x < 3) {
  x <- x + 5
} else {
  x <- 2 * x
}

x

[1] 2

This cell introduces the `ifelse()` function, which is a vectorized version of the `if-else` statement. It applies a condition to each element of a vector `x` and returns a new vector based on the true or false outcome for each element.

In [19]:
x <- 1:10

ifelse(x < 6, x^2, x + 1)

 [1]  1  4  9 16 25  7  8  9 10 11

This cell is a repeat of the previous `ifelse()` example, showing its behavior for a vector `x` from 1 to 10.

In [20]:
x <- 1:10

ifelse(x < 6, x^2, x + 1)

 [1]  1  4  9 16 25  7  8  9 10 11

This cell demonstrates the `switch()` function with a numeric index. It selects the Nth argument based on the value of the first argument (2 in this case), returning 'banana'.

In [21]:
switch(2, "apple", "banana", "orange")

[1] "banana"

This cell demonstrates the `switch()` function with a string as the first argument. It matches the string 'colour' to the named argument `colour = "blue"` and returns 'blue'.

In [22]:
switch(
  "colour",
  colour = "blue",
  gender = "male",
  volume = 50
)

[1] "blue"

This cell shows two examples of `switch()`: one with a numeric index that doesn't match any argument (returning `NULL`), and another with a string index 'size' that also doesn't match any named argument, resulting in `NULL`.

In [24]:
switch(4, "apple", "banana", "orange")
switch(
  "size",
  colour = "blue",
  gender = "male",
  volume = 50
)

This cell demonstrates the `which()` function to find the indices of elements in a vector `x` that satisfy various logical conditions (equality, inequality, greater than).

In [25]:
x <- c(10, 15, 8, 14, 6, 12)

x

which(x == 14)

which(x != 12)

which(x > 10)

[1] 10 15  8 14  6 12

[1] 4

[1] 1 2 3 4 5

[1] 2 4 6

This cell creates a 3x3 matrix named `x` and then prints its content.

In [26]:
x <- matrix(
  nrow = 3,
  ncol = 3,
  data = 1:9
)

x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

This cell creates the same 3x3 matrix `x` and then uses `which()` to find the linear indices of elements that are odd (i.e., have a remainder of 1 when divided by 2).

In [27]:
x <- matrix(
  nrow = 3,
  ncol = 3,
  data = 1:9
)

x

which(x %% 2 == 1)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1 3 5 7 9

This cell uses `which()` with `arr.ind = TRUE` to return the row and column indices of elements in matrix `x` that are odd, rather than linear indices.

In [28]:
which(x %% 2 == 1, arr.ind = TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3